# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'calculadora.old.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QLineEdit, QPushButton,
    QSizePolicy, QToolButton, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(305, 371)
        self.numero_1 = QPushButton(Dialog)
        self.numero_1.setObjectName(u"numero_1")
        self.numero_1.setGeometry(QRect(10, 110, 71, 51))
        font = QFont()
        font.setFamilies([u"Muli"])
        font.setPointSize(22)
        font.setBold(True)
        self.numero_1.setFont(font)
        self.numero_1.setFocusPolicy(Qt.NoFocus)
        self.numero_1.setCheckable(False)
        self.numero_1.setChecked(False)
        self.numero_5 = QPushButton(Dialog)
        self.numero_5.setObjectName(u"numero_5")
        self.numero_5.setGeometry(QRect(80, 160, 71, 51))
        self.numero_5.setFont(font)
        self.numero_5.setFocusPolicy(Qt.NoFocus)
        self.numero_5.setCheckable(False)
        self.numero_5.setChecked(False)
        self.numero_8 = QPushButton(Dialog)
        self.numero_8.setObjectName(u"numero_8")
        self.numero_8.setGeometry(QRect(80, 210, 71, 51))
        self.numero_8.setFont(font)
        self.numero_8.setFocusPolicy(Qt.NoFocus)
        self.numero_8.setCheckable(False)
        self.numero_8.setChecked(False)
        self.numero_7 = QPushButton(Dialog)
        self.numero_7.setObjectName(u"numero_7")
        self.numero_7.setGeometry(QRect(10, 210, 71, 51))
        self.numero_7.setFont(font)
        self.numero_7.setFocusPolicy(Qt.NoFocus)
        self.numero_7.setCheckable(False)
        self.numero_7.setChecked(False)
        self.numero_4 = QPushButton(Dialog)
        self.numero_4.setObjectName(u"numero_4")
        self.numero_4.setGeometry(QRect(10, 160, 71, 51))
        self.numero_4.setFont(font)
        self.numero_4.setFocusPolicy(Qt.NoFocus)
        self.numero_4.setCheckable(False)
        self.numero_4.setChecked(False)
        self.numero_3 = QPushButton(Dialog)
        self.numero_3.setObjectName(u"numero_3")
        self.numero_3.setGeometry(QRect(150, 110, 71, 51))
        font1 = QFont()
        font1.setFamilies([u"MS Shell Dlg 2"])
        font1.setPointSize(22)
        font1.setBold(False)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.numero_3.setFont(font1)
        self.numero_3.setFocusPolicy(Qt.NoFocus)
        self.numero_3.setCheckable(False)
        self.numero_3.setChecked(False)
        self.numero_2 = QPushButton(Dialog)
        self.numero_2.setObjectName(u"numero_2")
        self.numero_2.setGeometry(QRect(80, 110, 71, 51))
        font2 = QFont()
        font2.setFamilies([u"MS Shell Dlg 2"])
        font2.setPointSize(22)
        font2.setBold(False)
        self.numero_2.setFont(font2)
        self.numero_2.setFocusPolicy(Qt.NoFocus)
        self.numero_2.setCheckable(False)
        self.numero_2.setChecked(False)
        self.numero_6 = QPushButton(Dialog)
        self.numero_6.setObjectName(u"numero_6")
        self.numero_6.setGeometry(QRect(150, 160, 71, 51))
        self.numero_6.setFont(font)
        self.numero_6.setFocusPolicy(Qt.NoFocus)
        self.numero_6.setCheckable(False)
        self.numero_6.setChecked(False)
        self.numero_9 = QPushButton(Dialog)
        self.numero_9.setObjectName(u"numero_9")
        self.numero_9.setGeometry(QRect(150, 210, 71, 51))
        self.numero_9.setFont(font)
        self.numero_9.setFocusPolicy(Qt.NoFocus)
        self.numero_9.setCheckable(False)
        self.numero_9.setChecked(False)
        self.botao_apagar = QPushButton(Dialog)
        self.botao_apagar.setObjectName(u"botao_apagar")
        self.botao_apagar.setGeometry(QRect(220, 210, 71, 51))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI Black"])
        font3.setPointSize(22)
        font3.setBold(True)
        self.botao_apagar.setFont(font3)
        self.botao_apagar.setFocusPolicy(Qt.NoFocus)
        self.botao_apagar.setStyleSheet(u"background-color:rgb(220, 65, 166)")
        self.botao_apagar.setCheckable(False)
        self.botao_apagar.setChecked(False)
        self.botao_decimal = QPushButton(Dialog)
        self.botao_decimal.setObjectName(u"botao_decimal")
        self.botao_decimal.setGeometry(QRect(150, 260, 71, 51))
        font4 = QFont()
        font4.setFamilies([u"MS Sans Serif"])
        font4.setPointSize(22)
        font4.setBold(True)
        self.botao_decimal.setFont(font4)
        self.botao_decimal.setFocusPolicy(Qt.NoFocus)
        self.botao_decimal.setAutoFillBackground(False)
        self.botao_decimal.setStyleSheet(u"background-color: rgb(255, 210, 184)")
        self.botao_decimal.setCheckable(False)
        self.botao_decimal.setChecked(False)
        self.operador_menos = QPushButton(Dialog)
        self.operador_menos.setObjectName(u"operador_menos")
        self.operador_menos.setGeometry(QRect(220, 160, 71, 51))
        self.operador_menos.setFont(font4)
        self.operador_menos.setFocusPolicy(Qt.NoFocus)
        self.operador_menos.setStyleSheet(u"background-color: rgb(255, 210, 184)")
        self.operador_menos.setCheckable(False)
        self.operador_menos.setChecked(False)
        self.botao_resultado = QPushButton(Dialog)
        self.botao_resultado.setObjectName(u"botao_resultado")
        self.botao_resultado.setGeometry(QRect(220, 310, 71, 51))
        self.botao_resultado.setFont(font)
        self.botao_resultado.setStyleSheet(u"background-color:rgb(255, 170, 127)")
        self.botao_resultado.setCheckable(False)
        self.botao_resultado.setChecked(False)
        self.operador_dividir = QPushButton(Dialog)
        self.operador_dividir.setObjectName(u"operador_dividir")
        self.operador_dividir.setGeometry(QRect(10, 310, 71, 51))
        self.operador_dividir.setFont(font2)
        self.operador_dividir.setFocusPolicy(Qt.NoFocus)
        self.operador_dividir.setStyleSheet(u"background-color: rgb(255, 210, 184)")
        self.operador_dividir.setCheckable(False)
        self.operador_dividir.setChecked(False)
        self.operador_multiplicar = QPushButton(Dialog)
        self.operador_multiplicar.setObjectName(u"operador_multiplicar")
        self.operador_multiplicar.setEnabled(True)
        self.operador_multiplicar.setGeometry(QRect(10, 260, 71, 51))
        self.operador_multiplicar.setFont(font2)
        self.operador_multiplicar.setMouseTracking(False)
        self.operador_multiplicar.setFocusPolicy(Qt.NoFocus)
        self.operador_multiplicar.setStyleSheet(u"background-color: rgb(255, 210, 184)")
        self.operador_multiplicar.setCheckable(False)
        self.operador_multiplicar.setChecked(False)
        self.operador_multiplicar.setAutoDefault(True)
        self.operador_multiplicar.setFlat(False)
        self.operador_mais = QPushButton(Dialog)
        self.operador_mais.setObjectName(u"operador_mais")
        self.operador_mais.setGeometry(QRect(220, 110, 71, 51))
        self.operador_mais.setFont(font4)
        self.operador_mais.setFocusPolicy(Qt.NoFocus)
        self.operador_mais.setStyleSheet(u"background-color: rgb(255, 210, 184)")
        self.operador_mais.setCheckable(False)
        self.operador_mais.setChecked(False)
        self.botao_apagar_tudo = QPushButton(Dialog)
        self.botao_apagar_tudo.setObjectName(u"botao_apagar_tudo")
        self.botao_apagar_tudo.setGeometry(QRect(220, 260, 71, 51))
        self.botao_apagar_tudo.setFont(font3)
        self.botao_apagar_tudo.setFocusPolicy(Qt.NoFocus)
        self.botao_apagar_tudo.setStyleSheet(u"background-color:rgb(235, 50, 10)")
        self.botao_apagar_tudo.setCheckable(False)
        self.botao_apagar_tudo.setChecked(False)
        self.operador_percentagem = QPushButton(Dialog)
        self.operador_percentagem.setObjectName(u"operador_percentagem")
        self.operador_percentagem.setGeometry(QRect(150, 310, 71, 51))
        self.operador_percentagem.setFont(font2)
        self.operador_percentagem.setFocusPolicy(Qt.NoFocus)
        self.operador_percentagem.setStyleSheet(u"background-color: rgb(255, 210, 184)")
        self.operador_percentagem.setCheckable(False)
        self.operador_percentagem.setChecked(False)
        self.numero_0 = QPushButton(Dialog)
        self.numero_0.setObjectName(u"numero_0")
        self.numero_0.setGeometry(QRect(80, 260, 71, 51))
        self.numero_0.setFont(font)
        self.numero_0.setFocusPolicy(Qt.NoFocus)
        self.numero_0.setCheckable(False)
        self.numero_0.setChecked(False)
        self.toolButton = QToolButton(Dialog)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(270, 0, 25, 19))
        self.fonte_display = QLineEdit(Dialog)
        self.fonte_display.setObjectName(u"fonte_display")
        self.fonte_display.setGeometry(QRect(10, 20, 281, 71))
        font5 = QFont()
        font5.setBold(True)
        self.fonte_display.setFont(font5)
        self.fonte_display.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.fonte_display.setStyleSheet(u"QLineEdit {\n"
"    background-color: transparent;\n"
"    color: #000000;\n"
"    font-size: 48px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"}")
        self.fonte_display.setReadOnly(True)
        self.botao_sinal = QPushButton(Dialog)
        self.botao_sinal.setObjectName(u"botao_sinal")
        self.botao_sinal.setGeometry(QRect(80, 310, 71, 51))
        self.botao_sinal.setFont(font2)
        self.botao_sinal.setFocusPolicy(Qt.NoFocus)
        self.botao_sinal.setStyleSheet(u"background-color: rgb(255, 210, 184)")
        self.botao_sinal.setCheckable(False)
        self.botao_sinal.setChecked(False)

        self.retranslateUi(Dialog)

        self.operador_multiplicar.setDefault(False)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.numero_1.setText(QCoreApplication.translate("Dialog", u"1", None))
        self.numero_5.setText(QCoreApplication.translate("Dialog", u"5", None))
        self.numero_8.setText(QCoreApplication.translate("Dialog", u"8", None))
        self.numero_7.setText(QCoreApplication.translate("Dialog", u"7", None))
        self.numero_4.setText(QCoreApplication.translate("Dialog", u"4", None))
        self.numero_3.setText(QCoreApplication.translate("Dialog", u"3", None))
        self.numero_2.setText(QCoreApplication.translate("Dialog", u"2", None))
        self.numero_6.setText(QCoreApplication.translate("Dialog", u"6", None))
        self.numero_9.setText(QCoreApplication.translate("Dialog", u"9", None))
        self.botao_apagar.setText(QCoreApplication.translate("Dialog", u"\u232b", None))
        self.botao_decimal.setText(QCoreApplication.translate("Dialog", u".", None))
        self.operador_menos.setText(QCoreApplication.translate("Dialog", u"-", None))
        self.botao_resultado.setText(QCoreApplication.translate("Dialog", u"=", None))
        self.operador_dividir.setText(QCoreApplication.translate("Dialog", u"\u00f7", None))
        self.operador_multiplicar.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.operador_mais.setText(QCoreApplication.translate("Dialog", u"+", None))
        self.botao_apagar_tudo.setText(QCoreApplication.translate("Dialog", u"CE", None))
        self.operador_percentagem.setText(QCoreApplication.translate("Dialog", u"%", None))
        self.numero_0.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.toolButton.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.fonte_display.setText(QCoreApplication.translate("Dialog", u"dddd", None))
        self.botao_sinal.setText(QCoreApplication.translate("Dialog", u"+/-", None))
    # retranslateUi

